---
# mod_sslインストール
- name: install mod_ssl
  yum:
    name:
      - mod_ssl
    state: present

- name: change cert
  template:
    src: ../templates/{{ item }}
    dest: /etc/httpd/conf.d/
    owner: root
    group: root
    mode: 0644
  with_items:
    - ssl.conf
